In [190]:
import pandas as pd 
movies=pd.read_csv("movies_metadata.csv")

analysis = movies[["genres","imdb_id","overview","title"]]
#for row in analysis["genres"]:
    #print(row)
analysis.tail(20)

c:\python38\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,genres,imdb_id,overview,title
45446,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",tt0127948,A man rents an apartment and furnishes it in r...,The Devilish Tenant
45447,[],tt0135631,The background of this picture represents a sc...,The Untameable Whiskers
45448,[],tt0224286,This shows a prince entering upon the stage of...,The Imperceptable Transmutations
45449,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",tt0457437,"It's Halloween in the 100 Acre Wood, and Roo's...",Pooh's Heffalump Halloween Movie
45450,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",tt0135453,A band-leader has arranged seven chairs for th...,The One-Man Band
45451,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",tt0135571,A series of fantastical wrestling matches.,The Fat and Lean Wrestling Match
45452,"[{'id': 99, 'name': 'Documentary'}]",tt3054038,"Deep Hearts is a film about the Bororo Fulani,...",Deep Hearts
45453,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",tt5690142,The bliss of a biology teacher’s family life i...,Mom
45454,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt4130180,The Morning After is a feature film that consi...,The Morning After
45455,[],tt0069215,Sentenced to life imprisonment for illegal act...,St. Michael Had a Rooster
45456,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",tt0038621,An unsuccessful sculptor saves a madman named ...,House of Horrors
45457,"[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...",tt0265736,"In this true-crime documentary, we delve into ...",Shadow of the Blair Witch
45458,"[{'id': 27, 'name': 'Horror'}]",tt0252966,A film archivist revisits the story of Rustin ...,The Burkittsville 7
45459,"[{'id': 878, 'name': 'Science Fiction'}]",tt0112613,It's the year 3000 AD. The world's most danger...,Caged Heat 3000
45460,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",tt0102797,"Yet another version of the classic epic, with ...",Robin Hood
45461,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",tt6209470,Rising and falling between a man and woman.,Subdue
45462,"[{'id': 18, 'name': 'Drama'}]",tt2028550,An artist struggles to finish his work while a...,Century of Birthing
45463,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",tt0303758,"When one of her hits goes wrong, a professiona...",Betrayal
45464,[],tt0008536,"In a small town live two brothers, one a minis...",Satan Triumphant
45465,[],tt6980792,50 years after decriminalisation of homosexual...,Queerama

# fixed Imdb Link column as imdb_id because with imdb_id we can define the movies in every movie_dataset.csv . imdb_link is common attribute in every movies dataset .

In [266]:
imdb_ids = pd.read_csv("MovieGenre.csv",encoding='latin-1')
ids_list=imdb_ids[["Imdb Link","Genre","Title"]]
ids=[]
def listToString(s):  
    str1 = "" 
    return (str1.join(s))

for row in ids_list["Imdb Link"]:
    liste=row.split("/")
    l=list(liste[4])
    l.insert(2,"0")
    ids.append(listToString(l))
    
ids_list["Imdb Link"]=ids
ids_list.tail(20)

<ipython-input-266-ef7f59ffaf8c>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ids_list["Imdb Link"]=ids

,Imdb Link,Genre,Title
40088,tt03510654,Documentary|Music,Breadcrumb Trail (2014)
40089,tt05957584,Drama,Girl in the Box (2016)
40090,tt03551954,Documentary|Adventure|Biography,Raiders!: The Story of the Greatest Fan Film E...
40091,tt02281239,Documentary|Adventure|Comedy,Finding Truelove (2012)
40092,tt047495,Western,Silver Lode (1954)
40093,tt04504438,Documentary|Crime|Family,Dream/Killer (2015)
40094,tt02145909,Horror,The Forgotten (2014)
40095,tt02320388,Thriller,Hidden in the Woods (2016)
40096,tt04882174,Drama,37 (2016)
40097,tt0105041,Drama|Thriller,Obsessed (1992)
40098,tt0229480,Horror|Mystery|Thriller,Island of Blood (1982)
40099,tt093991,Action|Adventure|Comedy,Slave Girls from Beyond Infinity (1987)
40100,tt098216,Action|Adventure|Sci-Fi,Roller Blade Warriors: Taken by Force (1989)
40101,tt088757,Action|Crime|Thriller,Avenging Angel (1985)
40102,tt083291,Action|Thriller,Los violadores (1981)
40103,tt083168,Drama,Tanya's Island (1980)
40104,tt082875,Comedy,Pacific Banana (1981)
40105,tt0815258,Horror,Werewolf in a Womens Prison (2006)
40106,tt079142,Action|Comedy,Xiao zi ming da (1979)
40107,tt070710,Crime|Drama|Thriller,Snatched (1973)

# here we comparasion imdb_id and adjust Genre column as correct and what we want .

In [195]:
import numpy as np 

getAnalysis=analysis.merge(ids_list,how='inner',left_on='imdb_id',right_on='Imdb Link')
getAnalysis=getAnalysis[["imdb_id","overview","title","Genre","Title"]]
getAnalysis.tail(20)

,imdb_id,overview,title,Genre,Title
14327,tt0369347,A Navajo shaman is the prime suspect in a murd...,Coyote Waits,Mystery,Coyote Waits (2003)
14328,tt0367135,Officers Leaphorn and Chee search for a missin...,A Thief Of Time,Mystery,A Thief of Time (2004)
14329,tt0986272,A cheerful parking attendant considers it his ...,Validation,Short|Comedy|Romance,Validation (2007)
14330,tt0830184,A teenage girl has problems with her family an...,Where Souls Go,Drama,Kuhu pÌµgenevad hinged (2007)
14331,tt0294916,Kick the Moon is about two high school student...,Kick the Moon,Comedy|Drama,Kick the Moon (2001)
14332,tt0222150,"At a rundown bus station in rural Cuba, the li...",The Waiting List,Comedy|Drama|Romance,Lista de espera (2000)
14333,tt0388828,New York attorney Libby (Juliette Lewis) is a ...,Chasing Freedom,Drama,Chasing Freedom (2004)
14334,tt0118743,Cyril and Fiona are a long-married couple who ...,The Blood Oranges,Drama,The Blood Oranges (1997)
14335,tt0186906,A crusty old General leads his dotty family on...,By the Sea,Comedy,By the Sea (1982)
14336,tt0313579,"Charlene Choi plays Yee, a beautiful young gir...",Funeral March,Romance,Seung joi ngo sam (2001)
14337,tt0108700,"Chronicles the sport's signature people, place...",Baseball,Documentary|History|Sport,Baseball
14338,tt0249751,Influenced by the worldwide success of Italian...,London in the Raw,Documentary,London in the Raw (1965)
14339,tt0168136,"The sensational follow-up to ""London in the Ra...",Primitive London,Documentary,Primitive London (1965)
14340,tt0171546,A widowed theatre director moves to a small Co...,Murder in a Small Town,Crime|Thriller|Mystery,Murder in a Small Town (1999)
14341,tt0882820,Camila is in her mid-twenties and her life has...,Camila Jam,Drama,Camila Jam (2007)
14342,tt0105041,Lorie Brindel works at an insurance company an...,Obsessed,Drama|Thriller,Obsessed (1992)
14343,tt0229480,A movie company is filming a murder mystery on...,Island of Blood,Horror|Mystery|Thriller,Island of Blood (1982)
14344,tt0815258,No overview found.,Werewolf in a Women's Prison,Horror,Werewolf in a Womens Prison (2006)
14345,tt0185906,Drawn from interviews with survivors of Easy C...,Band of Brothers,Action|Drama|History,Band of Brothers
14346,tt0238304,Playboy does to softcore sex films what HBO's ...,Inside Out 3,Comedy|Drama|Romance,Inside Out III (1992)

In [202]:
#getAnalysis['Genre'] = getAnalysis['Genre'].apply(lambda x: x.split("|"))
getAnalysis=getAnalysis.dropna(how='any')

getAnalysis['Genres'] = getAnalysis['Genre'].apply(lambda x: listToString(x).split("|"))
getAnalysis

,imdb_id,overview,title,Genre,Title,Genres
0,tt0114709,"Led by Woody, Andy's toys live happily in his ...",Toy Story,"[Animation, Adventure, Comedy]",Toy Story (1995),[AnimationAdventureComedy]
1,tt0113497,When siblings Judy and Peter discover an encha...,Jumanji,"[Action, Adventure, Family]",Jumanji (1995),[ActionAdventureFamily]
2,tt0113228,A family wedding reignites the ancient feud be...,Grumpier Old Men,"[Comedy, Romance]",Grumpier Old Men (1995),[ComedyRomance]
3,tt0114885,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale,"[Comedy, Drama, Romance]",Waiting to Exhale (1995),[ComedyDramaRomance]
4,tt0113041,Just when George Banks has recovered from his ...,Father of the Bride Part II,"[Comedy, Family, Romance]",Father of the Bride Part II (1995),[ComedyFamilyRomance]
...,...,...,...,...,...,...
14342,tt0105041,Lorie Brindel works at an insurance company an...,Obsessed,"[Drama, Thriller]",Obsessed (1992),[DramaThriller]
14343,tt0229480,A movie company is filming a murder mystery on...,Island of Blood,"[Horror, Mystery, Thriller]",Island of Blood (1982),[HorrorMysteryThriller]
14344,tt0815258,No overview found.,Werewolf in a Women's Prison,[Horror],Werewolf in a Womens Prison (2006),[Horror]
14345,tt0185906,Drawn from interviews with survivors of Easy C...,Band of Brothers,"[Action, Drama, History]",Band of Brothers,[ActionDramaHistory]
14346,tt0238304,Playboy does to softcore sex films what HBO's ...,Inside Out 3,"[Comedy, Drama, Romance]",Inside Out III (1992),[ComedyDramaRomance]

## Find all genres in our dataframe

In [244]:
genre=[]
for row in getAnalysis["Genre"]:
    for gen in row:
        genre.append(gen)
genre=set(genre)
genre

{'Action',
 'Adult',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'News',
 'Romance',
 'Sci-Fi',
 'Short',
 'Sport',
 'Talk-Show',
 'Thriller',
 'War',
 'Western'}

# there is count of the genre how many times dupliceted

In [242]:
from itertools import combinations
from collections import Counter

count = Counter()

count.update(Counter(combinations(genre, 1)))

for key,value in count.most_common(10):
    print(key, value)

('Drama',) 7408
('Comedy',) 4768
('Romance',) 2418
('Action',) 2137
('Crime',) 2027
('Thriller',) 1793
('Adventure',) 1385
('Horror',) 1271
('Documentary',) 1240
('Family',) 890

# There is Action movie overview analysis with how many words in overview ...

In [263]:
ActionList=[]
for a,b in zip(getAnalysis["Genre"],getAnalysis["overview"]):
    try:
        if(a.index('Action')>=0):
            ActionList.append(b)
    except:
        pass
actionWords=[]
for w in ActionList:
    words=w.split(" ")
    for wrd in words:
        if(len(wrd)>3):
            actionWords.append(wrd)
englishGrammar=["with","that","from","their","they","into","when","When","must","this","have","after","only","find","will",
                "which","them","back","been","about","After","where","world","gets","film"]
for i in englishGrammar:
    for j in actionWords:
        if(i==j):
            actionWords.remove(j)
    
count = Counter()

count.update(Counter(combinations(actionWords, 1)))

for key,value in count.most_common(20):
        print(key,value)

('young',) 215
('against',) 184
('life',) 166
('help',) 159
('police',) 154
('finds',) 150
('take',) 143
('time',) 136
('group',) 135
('stop',) 130
('being',) 129
('between',) 124
('story',) 121
('years',) 120
('love',) 120
('save',) 117
('evil',) 116
('before',) 116
('team',) 116
('former',) 116

# There is Comedy movie overview analysis with how many words in overview ...

In [265]:
comedyList=[]
for a,b in zip(getAnalysis["Genre"],getAnalysis["overview"]):
    try:
        if(a.index('Comedy')>=0):
            comedyList.append(b)
    except:
        pass
comedyWords=[]
for w in comedyList:
    words=w.split(" ")
    for wrd in words:
        if(len(wrd)>3):
            comedyWords.append(wrd)
englishGrammar=["with","that","from","their","they","into","when","When","must","this","have","after","only","find","will",
                "which","them","back","been","about","After","where","world","gets","film","while","being","more","make"]
for i in englishGrammar:
    for j in comedyWords:
        if(i==j):
            comedyWords.remove(j)
    
count = Counter()

count.update(Counter(combinations(comedyWords, 1)))

for key,value in count.most_common(20):
        print(key,value)

('life',) 554
('young',) 523
('love',) 487
('family',) 389
('finds',) 364
('story',) 303
('help',) 281
('woman',) 277
('friends',) 272
('just',) 268
('take',) 268
('other',) 268
('time',) 262
('comedy',) 258
('lives',) 240
('girl',) 240
('meets',) 237
('school',) 235
('becomes',) 232
('wants',) 228